# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1313, 910)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_fileOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fileOpen.setGeometry(QtCore.QRect(320, 40, 261, 61))
        self.btn_fileOpen.setObjectName("btn_fileOpen")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(70, 50, 240, 180))
        self.label_img.setMaximumSize(QtCore.QSize(480, 360))
        self.label_img.setAutoFillBackground(True)
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.label_imageSize = QtWidgets.QLabel(self.centralwidget)
        self.label_imageSize.setGeometry(QtCore.QRect(170, 270, 141, 41))
        self.label_imageSize.setText("")
        self.label_imageSize.setObjectName("label_imageSize")
        self.label_frame = QtWidgets.QLabel(self.centralwidget)
        self.label_frame.setGeometry(QtCore.QRect(170, 310, 141, 41))
        self.label_frame.setText("")
        self.label_frame.setObjectName("label_frame")
        self.label_imageSize_ = QtWidgets.QLabel(self.centralwidget)
        self.label_imageSize_.setGeometry(QtCore.QRect(60, 270, 111, 41))
        self.label_imageSize_.setObjectName("label_imageSize_")
        self.label_frame_ = QtWidgets.QLabel(self.centralwidget)
        self.label_frame_.setGeometry(QtCore.QRect(60, 310, 111, 41))
        self.label_frame_.setObjectName("label_frame_")
        self.label_path_ = QtWidgets.QLabel(self.centralwidget)
        self.label_path_.setGeometry(QtCore.QRect(60, 230, 111, 41))
        self.label_path_.setObjectName("label_path_")
        self.label_path = QtWidgets.QLabel(self.centralwidget)
        self.label_path.setGeometry(QtCore.QRect(170, 230, 411, 41))
        self.label_path.setText("")
        self.label_path.setObjectName("label_path")
        self.btn_process = QtWidgets.QPushButton(self.centralwidget)
        self.btn_process.setGeometry(QtCore.QRect(320, 120, 261, 61))
        self.btn_process.setObjectName("btn_process")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(170, 350, 141, 41))
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.label_time_ = QtWidgets.QLabel(self.centralwidget)
        self.label_time_.setGeometry(QtCore.QRect(60, 350, 111, 41))
        self.label_time_.setObjectName("label_time_")
        self.label_fps = QtWidgets.QLabel(self.centralwidget)
        self.label_fps.setGeometry(QtCore.QRect(440, 310, 141, 41))
        self.label_fps.setText("")
        self.label_fps.setObjectName("label_fps")
        self.label_fps_ = QtWidgets.QLabel(self.centralwidget)
        self.label_fps_.setGeometry(QtCore.QRect(330, 310, 111, 41))
        self.label_fps_.setObjectName("label_fps_")
        self.label_length_ = QtWidgets.QLabel(self.centralwidget)
        self.label_length_.setGeometry(QtCore.QRect(330, 270, 111, 41))
        self.label_length_.setObjectName("label_length_")
        self.label_length = QtWidgets.QLabel(self.centralwidget)
        self.label_length.setGeometry(QtCore.QRect(440, 270, 141, 41))
        self.label_length.setText("")
        self.label_length.setObjectName("label_length")
        self.label_fileSize_ = QtWidgets.QLabel(self.centralwidget)
        self.label_fileSize_.setGeometry(QtCore.QRect(330, 350, 111, 41))
        self.label_fileSize_.setObjectName("label_fileSize_")
        self.label_fileSize = QtWidgets.QLabel(self.centralwidget)
        self.label_fileSize.setGeometry(QtCore.QRect(440, 350, 141, 41))
        self.label_fileSize.setText("")
        self.label_fileSize.setObjectName("label_fileSize")
        self.btnStartcompare = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartcompare.setGeometry(QtCore.QRect(720, 290, 261, 41))
        self.btnStartcompare.setObjectName("btnStartcompare")
        self.listView2 = QtWidgets.QListView(self.centralwidget)
        self.listView2.setGeometry(QtCore.QRect(860, 90, 121, 192))
        self.listView2.setObjectName("listView2")
        self.listView1 = QtWidgets.QListView(self.centralwidget)
        self.listView1.setGeometry(QtCore.QRect(720, 90, 121, 192))
        self.listView1.setObjectName("listView1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(720, 60, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(860, 60, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_show1 = QtWidgets.QLabel(self.centralwidget)
        self.label_show1.setGeometry(QtCore.QRect(10, 420, 640, 360))
        self.label_show1.setMaximumSize(QtCore.QSize(640, 360))
        self.label_show1.setAutoFillBackground(True)
        self.label_show1.setText("")
        self.label_show1.setObjectName("label_show1")
        self.label_show2 = QtWidgets.QLabel(self.centralwidget)
        self.label_show2.setGeometry(QtCore.QRect(660, 420, 640, 360))
        self.label_show2.setMaximumSize(QtCore.QSize(640, 360))
        self.label_show2.setAutoFillBackground(True)
        self.label_show2.setText("")
        self.label_show2.setObjectName("label_show2")
        self.label_sim_title = QtWidgets.QLabel(self.centralwidget)
        self.label_sim_title.setGeometry(QtCore.QRect(860, 790, 91, 41))
        self.label_sim_title.setObjectName("label_sim_title")
        self.label_sim = QtWidgets.QLabel(self.centralwidget)
        self.label_sim.setGeometry(QtCore.QRect(950, 790, 141, 41))
        self.label_sim.setText("")
        self.label_sim.setObjectName("label_sim")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 0, 471, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(720, 0, 261, 31))
        self.label_5.setObjectName("label_5")
        self.btn_change2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change2.setGeometry(QtCore.QRect(900, 370, 151, 41))
        self.btn_change2.setObjectName("btn_change2")
        self.btn_change1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change1.setGeometry(QtCore.QRect(250, 380, 151, 41))
        self.btn_change1.setObjectName("btn_change1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1313, 25))
        self.menubar.setObjectName("menubar")
        self.menuOpmlify = QtWidgets.QMenu(self.menubar)
        self.menuOpmlify.setObjectName("menuOpmlify")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menuOpmlify.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_fileOpen.clicked.connect(MainWindow.open_file)
        self.btn_process.clicked.connect(MainWindow.process)
        self.btnStartcompare.clicked.connect(MainWindow.start_render)
        self.btn_change1.clicked.connect(MainWindow.change1)
        self.btn_change2.clicked.connect(MainWindow.change2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_fileOpen.setText(_translate("MainWindow", "Open File"))
        self.label_imageSize_.setText(_translate("MainWindow", "Image Size: "))
        self.label_frame_.setText(_translate("MainWindow", "Frames: "))
        self.label_path_.setText(_translate("MainWindow", "Path: "))
        self.btn_process.setText(_translate("MainWindow", "Processing"))
        self.label_time_.setText(_translate("MainWindow", "Expected Time: "))
        self.label_fps_.setText(_translate("MainWindow", "fps: "))
        self.label_length_.setText(_translate("MainWindow", "length: "))
        self.label_fileSize_.setText(_translate("MainWindow", "File Size: "))
        self.btnStartcompare.setText(_translate("MainWindow", "Start Compare"))
        self.label.setText(_translate("MainWindow", "Model 1"))
        self.label_2.setText(_translate("MainWindow", "Model 2"))
        self.label_sim_title.setText(_translate("MainWindow", "Similarity:"))
        self.label_4.setText(_translate("MainWindow", "1] New Modeling"))
        self.label_5.setText(_translate("MainWindow", "2] View Model"))
        self.btn_change2.setText(_translate("MainWindow", "Change mode"))
        self.btn_change1.setText(_translate("MainWindow", "Change mode"))
        self.menuOpmlify.setTitle(_translate("MainWindow", "Opmlify"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

